### ISSUE TITLE
702的一些一己之见

### ISSUE THREAD

**Issue by lostpg** [jJayyyyyyy/USTC-2018-Summer-Course#1]
~~大佬是不是刷过PAT, 某些地方的风格似曾相识~~

这题我是没有用`queue`来记录, 甚至从头到尾都没有想到这题是一个 BFS, 所以也没有建图...
我直接用了结构体静态链表把每一门课的信息保存下来:
```C++
struct Curriculum {
  int num_pre_class;
  bool pre_class[MAXN];
} curriculum[MAXN];
```
然后每一个"学期"里都从未安排的课程里寻找`num_pre_class`为 0 的课程把它安排(得明明白白)上.
为了解决可以多线程安排课程的问题, 我设置了一个数组记录每门课的状态, 分别是"未安排", "本学期安排", "已经上完"三个状态. 目的是只在一次循环结束后才做"删除前驱课程"的动作. 在这里 BFS, 也就是你的解法使用`queue`解决了这个问题, 这是我当时没有想到的, BFS 的确更好地解决了这个问题.

今天看来自己的做法可以说是十分naïve... 我遇到的问题 BFS 都可以巧妙地规避了... 总的来说用BFS应该可以让代码更简单...
PS1: 缩进量好大!
PS2: [Line 31](https://github.com/jJayyyyyyy/USTC-2018-Summer-Course/blob/master/20180805/DailyTest/test2.cpp#L31) 的注释可能有一些歧义, 你想表达的应该是先找到所有入度为零的点放入`queue`, 没有可加入的点后将队列中的点输出并从其他课程的前驱中删除这些点....这样的意思吧.

PS3: 我也是跨考来的小萌新, 去年考过一次 PAT A~

**Comment by jJayyyyyyy** [comment]
@lostpg 卢大佬你好，首先感谢你的Issue~

1. 对的，刷过PAT，Solution在另一个[repo](https://github.com/jJayyyyyyy/OJ)

2. 关于702的拓扑排序，之前考浙大的时候做到过相关的模拟题，所以直接可以套模板。不过当时没有这题的分学期输出，只要求从小到大，所以用的是set。更多内容可以参考昨天实验 [readme](https://github.com/jJayyyyyyy/USTC-2018-Summer-Course/tree/master/20180805/DailyTest) 中的参考链接。

    然后昨天做到这个题目的时候，为了解决分学期输出的问题，突然想到其实这个和树的层序遍历有类似之处，而且最关键的是本题可以自定义结构，所以就在 `Course` 里面加了个 `term`，对于本学期的课程`now`和下学期的课程`next`，直接 `next.term = now.term + 1;` 就很方便了。

3. 缩进这个。。确实看上去有点大，我在ST里面都是用的tab，github把tab的宽度搞得太大了，把代码cp到IDE里面就恢复正常啦

4. 感谢大佬的建议，我去把L31的注释改改，加到具体的代码(L50~L57)后面。

5. ~~每天东哥都会在群里@一次卢大佬，说不定有什么不可告人的py交易（逃~~
